knife4j:
  enable: true
spring:
  datasource:
    username: fastapi
    password: DoAyv0VkoSOZACd
    url: jdbc:mysql://fastMysql:13306/fastapi?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    io.github.rainsoil.fastapi2: debug