### 登录
POST  http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username = admin &
password = 123456


### 开放的接口

GET  http://localhost:8080/test/piublicV




### 个人信息接口

GET  http://localhost:8080/test/info
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_22OMQrDMAxF76I5izMkNHuHQukF6g6KI6hoIgdbhkDI3avQDil0fP9_ibdCLj10gMPEAhWUTMlw9YAhxCJ6i3JeZk40eOg0FaqO1TWG109T9BkTK1O28P6wKNgpiTKO-d8vEuzHY7AbXHZ2XxCcyNB_HD1spknLbIPWNbVrm_q0vQHFtrfsxwAAAA.G7jne_fjtdnhiesu8FH1sf0XjEiBevvc9Q3PHiy4FlKTsJIrVnw67VaJ-hChmuAEJ8V7CNNj4sJW9UzoSfyg_w
