server:
  port: 12000
  undertow:
    direct-buffers: true
    buffer-size: 1024
    threads:
      worker: 8000
      io: 1000
spring:
  profiles:
    active: dev
  mvc:
    format:
      date: dd/MM/yyyy
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization: true

  flyway:
    ## 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: true
    #  如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 验证错误时 是否自动清除数据库 高危操作
    clean-on-validation-error: false
    encoding: utf-8
  extends:
    enable: true
    restful:
      enable: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      insert-strategy: not_empty
      update-strategy: not_empty
      where-strategy: not_empty
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.github.rainsoil.fastapi2.system
# knife4j的增强配置，不需要增强可以不配
knife4j:
  setting:
    language: zh_cn
    enable-version: true
  basic:
    enable: true
    username: fastapi
    password: fastapi
  cors: true